const data = "sixsrvldfour4seven\n" +
    "53hvhgchljnlxqjsgrhxgf1zfoureightmlhvvv\n" +
    "fives2dznl\n" +
    "twocrqvjsix5threethree\n" +
    "gtjtwonefourone6fouronefccmnpbpeightnine\n" +
    "seventdtrcseveneightsevencgjgjxfpmfsix8twones\n" +
    "fourthreeseven1grvhrjxklh3ninetwothree\n" +
    "fourninethrnnth8\n" +
    "two2hnxcfivejrdjxtb\n" +
    "bssbrgcx86vsmqstrxsjbjeightqzhbzxqg5\n" +
    "rsevenbqjfxh23rzdgcmdleightsixknpfs\n" +
    "jprxbcghdgxhk9x\n" +
    "8czzpmvgmlchnkf\n" +
    "vdrtteight85hlkninehgnblqnsdnineeight\n" +
    "fivetwohlxdql43kfzzbhtncg\n" +
    "lmhtwoneghgtl2\n" +
    "drtfsfhtbgfourpfpcznzrsix33\n" +
    "pptqkrdbeighteightsixdlsixkrlhr2\n" +
    "57threetwo\n" +
    "qoneight367gqbpbtbffivetlhrdjgnml2d\n" +
    "ninevdnzxsxone3\n" +
    "3threeqzrmfndfiveeight4\n" +
    "rmthreethreefourtwotkpncxpmctkxjhzxg5\n" +
    "nsfrpl6lkqrrmlxhrxmngzjtzbpsjgeight\n" +
    "9twobfknine57sixfour7\n" +
    "7one83sixthreecllxjnphb\n" +
    "82nhxcjnck1\n" +
    "5zrffive\n" +
    "bgdzqqpninefourjhtcjfjmxrmqhgz7fxnjrjfivetlpbddcsfs\n" +
    "xmbgqfhxx1sevenkfnqztfourzbngv\n" +
    "6onethree\n" +
    "1przkgcft77xblxkxm\n" +
    "hnjslmc96\n" +
    "fourktlnine59\n" +
    "7twoxthree\n" +
    "9twofiveonetwo5bnl\n" +
    "6cbzmrg1three7\n" +
    "fbndztsthreefourthreefgj1eightrffdbpsn\n" +
    "4zpqnskhnqjbjlhbbsxsmk\n" +
    "seventhree1fourbvnbbsbkl5\n" +
    "five42jkbzqcnblr\n" +
    "357\n" +
    "543cshpxrfnnhonetkbhxtmlgczdndqjscb\n" +
    "2mpftseven\n" +
    "44five8nineeight\n" +
    "rmgrljrljb8hxxfmdpbbvmblltxfive6mdsmm7mmpk\n" +
    "nprsix6\n" +
    "five4vkqrsixmjkjps\n" +
    "kfivebrlzvc1twoseveneight\n" +
    "lqnjsixtwo7fourbmbxnr9dqmpbbfkfive\n" +
    "1ccsvvrrvjseight9nzgnldhzndpvdzcncl\n" +
    "zdzlsix9rjvninehsix4\n" +
    "fsevenfour8four6three\n" +
    "eightrmvsq65mpvffkkhxc6seveneight\n" +
    "sixrmgchvfttpbsncc5hnine\n" +
    "147\n" +
    "57gsdhqjbrfsskhmtcbszmjmhrxg7\n" +
    "sevenfive31twomhkhttdprdnzlng7three\n" +
    "3spgnkpeighttwotwo4\n" +
    "psxlxdjrtmgpveightxjkxhmbeightsix2\n" +
    "five53vgqcfmgqlm5dkchcmfkclpfxntbf\n" +
    "76sixmgqgftzfive4nfsqhkqvptnnshqlhd\n" +
    "sevensixsevenone7xbsxvdpdtc\n" +
    "nine3sixfourtwo6mpmpjb\n" +
    "eight4sevensixfour7dtgrvpq\n" +
    "1sixnceight1bg\n" +
    "79xfftvpvfour\n" +
    "noneight3\n" +
    "twoxdhkkgxhvz5three9seven8hszqdvnhr\n" +
    "kbpc9kqvhonelljprfs4pzcnpfrdssfivetwo\n" +
    "four4eightseven\n" +
    "5three95cqs65nine3\n" +
    "72sevenrkcqmqbscp9kzjxrg8d6\n" +
    "5rjbzpghninexfzvjpqmt9eight\n" +
    "jfjrvzcjkrkd1eight\n" +
    "six4ccvbclxkkntzmgthreercsjbznfive\n" +
    "xkqdtghlshthreeninefive53three\n" +
    "one3fgcsrxk1\n" +
    "1foursevenmvmzpvkqseven351\n" +
    "858qqbkgjxqfive\n" +
    "fkpd4three8sixlkttgnfzc\n" +
    "btpmrzqmsevennine3f6\n" +
    "61nine\n" +
    "fourone7fsfxfrlqzvbqjpccfour\n" +
    "five85sseven7jxlpl\n" +
    "kzgszphcpfoursevenlzlkqmjndz4ninelnine\n" +
    "4eightld\n" +
    "five8dqzlzfnine\n" +
    "6zjsqxqnineplbqhxltmffour\n" +
    "1fivebfoursrdcfive\n" +
    "8678fourgzdhrtrtwothree\n" +
    "847\n" +
    "fiveeightdseven5fivefivecbdrrbnng\n" +
    "5qddhnzxlhqeight2sevenln8nine9\n" +
    "13kxvqlvt7xvcksdthreekfqc\n" +
    "1threehqshd9two19\n" +
    "twogcphmsspeight7\n" +
    "1pnktcbbpkmeight42hcgfoursix\n" +
    "nineninepdxqg4xspkqjneightchqxptninegcckrbmsvk\n" +
    "fnine5ninex1eightgdhpkngmgq\n" +
    "jlgvcn73three\n" +
    "twoljsp5\n" +
    "xlf52twovcnnjglhmm\n" +
    "lmonesix1kfhbpdntpthjkl\n" +
    "89six6threegmfqlone\n" +
    "ninefbdvbhrgfivesevenzsjlt5tqkzfxb9\n" +
    "pvfoursixgdtvxxvlnx8kgsj\n" +
    "9fpjsnheightfivermpxrkddczvzqbdbs\n" +
    "92zhksstbzr\n" +
    "fvxeightwoddrhpfsevenmlkp178\n" +
    "2ntqvj42eight6\n" +
    "46xthree26snkhxmmzknhrvsfrprch\n" +
    "lvcfiveseven3plzlsvmm\n" +
    "three69\n" +
    "scrkglnine1\n" +
    "fivemlvcpxfcggllpnpsdjmnhhkfkbtmcfone2\n" +
    "7tseveneightnmjqbsfgh\n" +
    "onegbdpmtwo39nvbdl2\n" +
    "532rg\n" +
    "3cpjksevenonejjndff9six\n" +
    "4nbtbrmtxmpcnvkjsgseven\n" +
    "2brfkknktcz\n" +
    "ghtshqhnmvmgdps6rclhhsix\n" +
    "eightj4hnnsfssqqmfourgdrmgcljdnslrhmkc\n" +
    "seveneight5pdzgpjvzlsxkjpflkjbzqhrfdlbskfbnbkcpl\n" +
    "six5gqjlsevenfnffpl2hrdrvrdthreeb\n" +
    "137nineone81one\n" +
    "gnrxrnqjdtxvcbggcmcfshz8rrkfd\n" +
    "nrlccp4szxqgljj31\n" +
    "622kvttthree3jfd\n" +
    "8zqgbdc\n" +
    "rmczlxrvjpp79sevenonefourmmjvgthree\n" +
    "3fournine185sevenrgtrrpgjf\n" +
    "five282six\n" +
    "three7xcqlxd16sixktfmxslk\n" +
    "6vrzsmsv8\n" +
    "4twodqjxsbklhjtfthree\n" +
    "3dmxljghfourzkvxq3\n" +
    "4lveighteight51tfgbbfour\n" +
    "csfkthreesixxcfpdone3tvscpp8three\n" +
    "vhmkkks6glrlpv\n" +
    "eighthnine1rsmbpndnqqgds\n" +
    "7tnbhktwofive84seven\n" +
    "3kjpxgrlmstnxxdnqgpgjhcttlmnineninesix5\n" +
    "2eight4264\n" +
    "twoqmvnmxstnqfour8d621kxktzk\n" +
    "pdksthree5gzpvlmjmfourtwocfbsthree\n" +
    "rtvtffd6fivefive\n" +
    "onemxrpmlxsbd9drnsfive3\n" +
    "zfjqcthreesixoned1sixsx\n" +
    "flsevenvqctldf6\n" +
    "1seventwoeight6\n" +
    "xxktlvdcdtstsqjmd47onell5\n" +
    "6tbvxcgddrfjnhgntrthreegx4\n" +
    "rfxjvdllvzv2dshhdtjvbxvsqmq4ninegp\n" +
    "five7bjzhkmmfnhcmnfljlhb6bptflhrrvgfour\n" +
    "ltzlonenine5six\n" +
    "nineeight49\n" +
    "fqcdtgtb9sevenrnsgx4\n" +
    "eightlfdmv5threehrrkvhzhhxmzprz\n" +
    "2dglljrllsix\n" +
    "sevensixxnlb473twotwopgjxgp\n" +
    "5sevenrkhk\n" +
    "9eight3\n" +
    "7one5four\n" +
    "lh5jzqxeight84\n" +
    "385nslvbjqvkxvvcprqghxccv87fpmqfhnlv\n" +
    "ngsjdpvv72sixmbtr\n" +
    "xvslr642\n" +
    "mrjhmtnhx2\n" +
    "gsrbhmh5fiveoneqhhmsmkrbc3sixtwoeight\n" +
    "mnxvtn3vtqhxsrfivefive57qrmhshkk\n" +
    "9vkghgztxdzcvl7dlthreefmklvsmhxnqrtzzsvvq\n" +
    "djclthdptrk8fournineqvnrrlbjjhtwoeight\n" +
    "79pnt9one9\n" +
    "mlcxcrjzpvlkkdpmmsevenone6npd\n" +
    "fivefiveninezhppshtks1kqtkss\n" +
    "7nine46cxzcjhbnbg5\n" +
    "fourqhbr5cqbdmvps\n" +
    "pqvzfrt7ftplx\n" +
    "265pninenine5twofive\n" +
    "four41\n" +
    "1fdgcmbc1onepcktj3seven\n" +
    "5twob\n" +
    "two1sixc7znfhkhzgzzjzf3xdbqtdspv\n" +
    "vqkg7sixrntjjzc\n" +
    "7one9zdnnqtbbq4gkkkdskbtlqspsmx1pphnh\n" +
    "xgsix2hltpnqxktwo\n" +
    "gmhmskd37nqk7q8\n" +
    "onezxllhcpjfkeightsjvvpmcztdndf8seven\n" +
    "ninenmrljg6fivegmtzhflztxn\n" +
    "nmzqxlx387eightczpsgxskfzklk9\n" +
    "1fournine7cgtmr2lsvljtp2\n" +
    "98lzz1sixfour1three6\n" +
    "one8ninetwo\n" +
    "4xcrhxlvsr7\n" +
    "8two2four\n" +
    "ninefninefour5qlxbmk51\n" +
    "hhlflbbmbd29jrjrbx5879\n" +
    "six3djmgs\n" +
    "cfivevgzckfqcg6ninesixfvlkpm\n" +
    "449honexjqtrxveight3nzzx\n" +
    "threetwo22\n" +
    "d6seventhreeeight949\n" +
    "nllbxt3qspvt6sixgglvfcfivetwo\n" +
    "jhfrfgjjtsseveneight76\n" +
    "gjninestxljz88six2\n" +
    "5rsqhsx9rnd\n" +
    "7three72sixjkxlnpt\n" +
    "dhkfvps9\n" +
    "onefive7qdvbqjxzk\n" +
    "7sevenldcfd7\n" +
    "twoeightpjpkcjvvbfseven6\n" +
    "six1eight9five29\n" +
    "hgdztcbpx4sixseven1fklt8six\n" +
    "6six7kjlpmld1\n" +
    "twolpxfhllfllkcksvsllbtvjsll2bjq\n" +
    "2nine7nine79fourfourbtqd\n" +
    "tjfsmthreeoneninendd6two\n" +
    "2five1\n" +
    "1seven1jrgtkcfsjfbfrmsevenfourlvbgbknn\n" +
    "79twolthjsjnbrthreerdmbk3\n" +
    "sevennine6432\n" +
    "1hjtcnjztkvjspr7\n" +
    "seven84dlbb1\n" +
    "two78threevdhgqfzt\n" +
    "7bmln29onezlxtzthj7fzpvnxllz\n" +
    "nldvscqn9hfnthreesevenonetwoflbrdnhq\n" +
    "sixpkx7eight1ctbhdf34\n" +
    "rprprpmfour3fivevxqrqrqp4tghglvssfive\n" +
    "gpxjnsrsonezn1bht\n" +
    "2three4ninebnfzzxzl8seven\n" +
    "two23one2\n" +
    "9sevennmxmxvzcpt3hgsprhmvtxbqvbn2three\n" +
    "69threeonervrxqdfive\n" +
    "scjjqgrbnnsztvmbtninethree74two2\n" +
    "one7nkbn6nine\n" +
    "nlmdfshone2eight11sqhsftrg\n" +
    "fxt4twofive3sevensevenxq\n" +
    "three6zfzpdmrpbr9289vszpcqkq\n" +
    "8threebqzbpz3\n" +
    "plpnsfour6\n" +
    "1twonetdm\n" +
    "oneseventwo4x\n" +
    "fourhmprhkfgdkgqznineeighteight2\n" +
    "984mrrqjhzc3dsqpjvrpctvbtk\n" +
    "onenjdmrjfdjznrffive73fivechpxdpnqbnpq\n" +
    "4mhjzvbgnxpq1jfllblcjkbxzrt\n" +
    "threeblztlfgltlznxv9cqsjfnmgftnmscjmxpmfkleight\n" +
    "jtvjjrjnf2two\n" +
    "8oneseven3djtdzseven3\n" +
    "bctvlxxxgtp4\n" +
    "onenrncdseven2foursixone\n" +
    "sevenseven1\n" +
    "cfhszdltcqkllpqbfive6sevenqjqphqkhhjsixbvblzhgfp\n" +
    "dpzbcnbdzzninev6eightlk\n" +
    "eightjznzkdg53fourninebsfdzqpsix\n" +
    "four4s88fdxtnt3six\n" +
    "nine33six15five6\n" +
    "eight3five26jdrrmvnzgxm\n" +
    "zjzpg4onesixseven\n" +
    "99fourfourtwo\n" +
    "xlxmvkdkvrfrddhvgmhrqllvcpsnine2\n" +
    "fourfour1xfpdnfqvcklf\n" +
    "ninethree7one2czbtzzfkz\n" +
    "two41hgvsfzmtcz13\n" +
    "sevenfour2sixq\n" +
    "seventdnjmqhbmm3zgffshmjlzcjcvbl7mzc\n" +
    "khthzgjkzdkgjzxlkrvd4fivezq5\n" +
    "fiveseven4onefourxtrfournine\n" +
    "9onexh\n" +
    "83ninet3drmkrtpdc6pmdrvdbx4\n" +
    "twofvxngqdhlpstlhfhxonegrrzfbsv7\n" +
    "seven3fivethreepqzfl7\n" +
    "56two229\n" +
    "djrthreethree3seven4zxlfntgssq\n" +
    "three3mdkbtxkkfour2gtpgcktqflrfs\n" +
    "711q3ninevbsg2\n" +
    "ninethreenfone4eightseven\n" +
    "onexfxnine64fivefour\n" +
    "foursqctmzlh64eight\n" +
    "8one4mslnine65fnr\n" +
    "9mbgn42bfhbfive79\n" +
    "75kdhhfllf1onesevenssvztltg24\n" +
    "jxrpsflt52jz246five\n" +
    "dlvhq4pzxcstjtxq9\n" +
    "lgnxqnhjsbsixpm24two\n" +
    "3sevenfiveltdmfzlq842four\n" +
    "threetwosix39foursixthreethree\n" +
    "nine12bkhqklpfour3\n" +
    "73534two1\n" +
    "nhkbzfmgdhjjhggfivebncmnbskphsixnine2five\n" +
    "xxzvlxmdtwo8threerbtwo1eight\n" +
    "5bvzltnmqgnfqvqk3fivefhhhhnb\n" +
    "qthree1fivettjdpgnmkcfive\n" +
    "tknsqnjjczfbgshtvpdchpb6fngjztk77four\n" +
    "1five2seven1rsqfsrxfcmnxtqj7nxzcc\n" +
    "lcvzgqpmlgonefourseventwosixnine8\n" +
    "ssqcjzpjb5five5two\n" +
    "seven7nrgglcjfour3two4\n" +
    "five4fivexnbnoneninengqngmg\n" +
    "8fiveltmhtwo\n" +
    "jzmqtqbzh1\n" +
    "1fourthree\n" +
    "2eightfoureight2\n" +
    "7nzkfvzfivemchbf\n" +
    "7four2tpfvmjgdseven7\n" +
    "1dzfpxmpxjscclshsixknfmgrpvptdf\n" +
    "rm4618bkgpgmrhdldbftqzssbzsqxsix\n" +
    "fivemmfxdgqpj7sevensh1nine\n" +
    "qgqxznine19sixeightone\n" +
    "one7sevencnpdqmv\n" +
    "vgm8four5ccrcnbddv2\n" +
    "28gxkg245hpmd\n" +
    "ngvvdk41eighttwoseven\n" +
    "1nine54\n" +
    "onehcvdnt7twonflthree\n" +
    "5nineseven\n" +
    "8x\n" +
    "fiveznsz56\n" +
    "mplrzchnhjgxfmqbpfdm7kzrfour4threehjt2\n" +
    "gdvjfqsqmnine67jlh9\n" +
    "4tphmcfm33sixvgonefour\n" +
    "61fourthree7ninethree\n" +
    "five4qsk42sixmxdrqcndcmvxcfqv\n" +
    "rkrstzqone3bjjpgfrgg4859\n" +
    "2oneqlsmvzznsxninefivesixksshvprpfive\n" +
    "6fouroneoneqffour6jpfqpvcmx\n" +
    "xshcfrdxnlv125nineone45\n" +
    "jqdvfiveglxjpbvzch9\n" +
    "6jqmjmqznqmxkztdgzb\n" +
    "tzjfdrzvzfivejsv49eightwozmf\n" +
    "rslmsmj4vnq71eightfive\n" +
    "vbmbfkfour26sz9\n" +
    "6two769hffxnbnineeightnine\n" +
    "9five3hqjdvxlmvvckndzhsix\n" +
    "jtknzpnbqpfgtdbnxkbthsix78\n" +
    "fivethreerht48llrprvphts9cd\n" +
    "eight19\n" +
    "sixone66six1seven\n" +
    "fsgtskzsk9eight6\n" +
    "2gb\n" +
    "onecone79g8\n" +
    "vgfqd49mk26qmxhqb\n" +
    "lclctndpsffrbdmztb8\n" +
    "1seven4\n" +
    "thxj66ffbzzkz6twolzsbqseven\n" +
    "2lrgrrhceight\n" +
    "332three9\n" +
    "dmtwonegppvjcmj2sqplmshfsd69\n" +
    "fqdmgxtwotmzrb549six7seven\n" +
    "87kkcbqvfftwomxsixsevenfrhlthree\n" +
    "82l15vjddqclrtttsm\n" +
    "2gjb3qhxvdrblq1\n" +
    "three4xvqb9nineone1fxsvj\n" +
    "921\n" +
    "4xzzdgzpklltssh95two\n" +
    "twoonejsmrddbtcng8zbhfbqvblbkmcpxst\n" +
    "8five949\n" +
    "pmpv69fourddfxzrvphdsxz6\n" +
    "seven6cnkkgphkdmvnxnxfvkfcmgthree\n" +
    "98three\n" +
    "threert9rfsix244\n" +
    "18jnzxfivefour1sixthreefjngk\n" +
    "543vlxckcffkj\n" +
    "crxdmtzone1\n" +
    "t99vqbpprvvzq3fz\n" +
    "1mfourdvpfour5dzzdnjbdfxchkgpbnlss\n" +
    "five11six5\n" +
    "9bbvmmxkfzldhjfghnlsevenfour3slnp\n" +
    "twokglseven1qqhsp57clctgc\n" +
    "kmtrnineseven6one2\n" +
    "four1rg8five\n" +
    "threefour5sixsix\n" +
    "mdvrfdcxndd1\n" +
    "hqtsplgzqbrxbbstwolzrjcnqf3threeq\n" +
    "drhoneight7bnjh3fiveninejlqlljd\n" +
    "fivefqqfcmzdfour1\n" +
    "94thphvvkmkhpdnqsrh\n" +
    "bsqhfjk3zxzhtqfncc7lcbzpgx\n" +
    "threezzjnlpgxhsfxmjl9588\n" +
    "fourfourn279six\n" +
    "fivevxzjpss5eight\n" +
    "5fourc8fivenine9hmdgxjeight\n" +
    "3threeninexjbzmsgrhkzxscfhddhsixtwohcgjfdszpxjsp\n" +
    "sixknhkfsmqvvvone9jhfxjpr\n" +
    "8bxgmbbdmrvpjfxbzd\n" +
    "1dpxrdfvp3two8one8one\n" +
    "threefbvbfkk3scsbr\n" +
    "gvmrjgjkdppdc9one\n" +
    "133gglhlfprmtnqb5four\n" +
    "vtzddchxktgsshpztmpxxvrhsjq1fkstwo\n" +
    "8one5krgr55\n" +
    "twofive8nine5\n" +
    "pnjpkthree47eightjbsdz72\n" +
    "sixonefhltgkbbbt8eightthreefour3\n" +
    "72gbr5\n" +
    "38mqgkbbkhbksqxfive61\n" +
    "8ckhzckrkq88threessqqcpbnonejtxkxbbfive\n" +
    "5threetwocrfsxsnf643\n" +
    "9tlgcxkr\n" +
    "threehbmttm59sevenhfourhpqrjqj\n" +
    "dfbqxtzkkpfseven42sevenseventwo\n" +
    "86eightfvxgfjzrf\n" +
    "vxfl4\n" +
    "three4bshflzvvdnbeightfqdlqnvlrkdxrtnpjcqn\n" +
    "5sevenpxdrhmjbgdgpnseven\n" +
    "2two4\n" +
    "9xxnhc8vqmrnffmg3\n" +
    "97kqfonefhhc4\n" +
    "8fiveseven9\n" +
    "nine6eight\n" +
    "52five3one2fkmnk\n" +
    "kfdxhkninestttsmtkmkhxbhhxlbxsix3pvdqd1\n" +
    "fourninedhsvphbmhccjcktqsnthree8\n" +
    "fivefive35three5four33\n" +
    "4seven7seventhree6\n" +
    "vfkjpfxltm5xcq5nine825\n" +
    "52onegczcpghmzxvgjglbpjrtseven\n" +
    "5zzlmvl\n" +
    "kmsnldpssvdfive519kvmlnthree7\n" +
    "lpkshkvrrl124dpgplnine88\n" +
    "644seven9qdpbpxdlxf\n" +
    "7jqc\n" +
    "cbhpmvs7\n" +
    "two7twoonebdmzftjjxrfmsix\n" +
    "5mxxmdzdqdsixfourone\n" +
    "3g6\n" +
    "fglrhqsseventhreefivedpq4\n" +
    "fivefiveglddjbfbk3two51eight\n" +
    "7eightfjqqhljpxgvlghsc9lfqctddsoneninetwo\n" +
    "mllcz8vczcgrbdn41qfglhzsqk\n" +
    "gxstgzqfrfourgkxvnkpgckhnxj7seven\n" +
    "93sevenjzvxc73\n" +
    "63nine135gqdhbnine\n" +
    "ltcgbbxftssixdgtxdpp1kzbhvqt\n" +
    "2z3seven1\n" +
    "4two9qnfrvcbonesixzfr5\n" +
    "twojhlt32\n" +
    "8one2eight\n" +
    "cdjdb4vcvg98\n" +
    "three9nc\n" +
    "qmfjqnsbthree97\n" +
    "fivenine5one\n" +
    "glnine55twoseven\n" +
    "three7k2\n" +
    "437five\n" +
    "svzrgbljxdstwo9six6four\n" +
    "383zseven2eight3xvqvp\n" +
    "6fivegnglqj8tfkfgxkm573seven\n" +
    "twosixltnpgkkr3\n" +
    "7sevenmphlgrdz72j\n" +
    "5nine24\n" +
    "hq9b4fourbgtjjgmzfj6\n" +
    "1sevenczhtpmvmstvvgrbrhptxtlneighttwo4\n" +
    "mbhfpxjbj1xdmvchpztmcxtlqjtk\n" +
    "37hrqnnknjpcmmfhnbbmsps\n" +
    "9fcsix51foursckzjtffvv\n" +
    "gddqlqfourninenine65\n" +
    "tgqvzvcnxs5lffnzhtd\n" +
    "3bqfb8psxv38five\n" +
    "fourcskck3seventhreefour8\n" +
    "six1sevenjdvjkrn6six88\n" +
    "threetwothreeone87jlhgbrtgvdrt\n" +
    "sevenmsldjlpvzhtwosix4threefour\n" +
    "cthhqm2oneeightfour\n" +
    "rpbbnszfxg8ninetbeightfiveqskfzcf\n" +
    "sbjghdfgheight9seven\n" +
    "nfj59pjhrzfourfive\n" +
    "twotwoseven6nxxblhkdxct8\n" +
    "5lgxnqdfiveninedtdonespkvnonelzphcrxr\n" +
    "7qkphfqbbjvninedprb8cgmpcmsz79\n" +
    "fkmhvlvjgczxsllskzdone8\n" +
    "dzjvft8fivecpclmdtwo5453oneightt\n" +
    "6bjbvjgm\n" +
    "64ckqzvnjdhnine\n" +
    "four5eightwon\n" +
    "six3vggtzjxtsjfpbqh\n" +
    "7one5\n" +
    "onezccmbfq3\n" +
    "7gseven3seven\n" +
    "nxsevenone6ninep\n" +
    "hmmz2hvmxcmqtsrxdllrnzrgzcx85three\n" +
    "mskcmjfdvxmxlv5dnhhkvhx\n" +
    "krxjnz48sixzpqzppcngmsixb\n" +
    "7threedgsgseveneight\n" +
    "nfhpdbs4988\n" +
    "fournnfsjtwosixtwo2fourcnvdgmcfive\n" +
    "ptfhmlmjzltftmn2nvxvksbqhl7two7gdxb\n" +
    "threehqgqzx32\n" +
    "598flbdmfivenine\n" +
    "1tvrxqvsixfour\n" +
    "threedz8fourthreencxs\n" +
    "8foursxvfourlrgqjh\n" +
    "31vjeight2nfgkjvjqseven\n" +
    "one2lvvlseven9\n" +
    "fournine5xtpl\n" +
    "2fgfbjg\n" +
    "2onefour\n" +
    "one3vbrbkjmkqxs9t\n" +
    "jdgcvgcfsdbhvmeightkf8onenine9\n" +
    "2onekqfmjcftms\n" +
    "seven68two4zn\n" +
    "sevenvqpmhtxhncvff5one\n" +
    "mfqgljnmonepldmbnqphhtdonefive3xr\n" +
    "rrxkcnineninebsh3sixnine\n" +
    "81ztjznine\n" +
    "mgkgddsonethreebpmhnpfnqjjhzthreehdpnzmht55\n" +
    "3five3\n" +
    "jeightwotwobqsbczrlfgj7\n" +
    "6pvghfqtfjc\n" +
    "three3onenine4pmtfive\n" +
    "rnrdbjxtwo7fivesevennlpfrcptqtwofiveone\n" +
    "7psthptpvbh2\n" +
    "4bvsgkshslg44vkfour\n" +
    "three1tworkxhhps\n" +
    "299one\n" +
    "rghnkhlxqz91\n" +
    "76twocfcrone3\n" +
    "97dkkfonen6jnsmlh\n" +
    "2hnqhcpr4\n" +
    "seven7llhskvhnxz4\n" +
    "6ffjvvdgbtdxpmvdsk5qvppxtgblpvl\n" +
    "btsl8threenvhjkcckkgfsfnjgthree49\n" +
    "31vvmjfz\n" +
    "hjbkfgnmk35four4kgxb3two\n" +
    "5zkljxdhzpcfb7five8zpsckrfkvbeight\n" +
    "8onefourtvdgninenfive\n" +
    "6eightzcvfourrzqp7\n" +
    "3foursevenxjkmnnvqhq\n" +
    "5274eightwohx\n" +
    "vktjgvnztldsfbnqgqt9seven35\n" +
    "j5xqqltd3fouronesix\n" +
    "4bnpgeightsxlrbxdsnbdc\n" +
    "3zzxtcs8\n" +
    "ddjd13zpfqqx\n" +
    "fivenmninerrzkdp1\n" +
    "oneone989bn\n" +
    "sixfltmpjjqnmfpln5\n" +
    "5ninedn\n" +
    "562\n" +
    "47eight8hqsvhpk\n" +
    "nreightwofjnkrsgcdnt75\n" +
    "four1qvdfsfthgbb3kjrlh\n" +
    "shtf21\n" +
    "cqdlfptg2zzninelsmgpvqvrqnz7\n" +
    "shsjvztwonine8fourgrtgbdfdlqjvmktnrt\n" +
    "xpjzeight9rr\n" +
    "56fourcjrnmttqp8two3\n" +
    "3sevennxshxncmcfnxpv\n" +
    "fourvjgpcsqfjmtwofour9nine\n" +
    "twogjvtlpnsmcjqkgkkj7fivefmmthrfs\n" +
    "four9kssrrzrlbqeight\n" +
    "three4eight1xzrqjpxpnxqptnqvmqsdj\n" +
    "6phjpjd\n" +
    "5twoklcnsq1xcone\n" +
    "seven1bvnpqqkqcmzdllhj23five\n" +
    "ff19sknzln8jrdlhptfourz\n" +
    "rdrtwonehvdxccpftplzfqpzcrjsix6pfr\n" +
    "seven3llthreeshcb\n" +
    "qqzlgseveneight6one15four\n" +
    "7pzmfpvzdhhnxpsxd4vrqbmgtxjcsvfxdnxjzsevenkd\n" +
    "threelvkggjfivemlddrfrrllgfssfmgs17\n" +
    "tcbckd2\n" +
    "7four7krmsixffv9threethree\n" +
    "glvknsmmgn2onexjdskcqq3threeeighttwo\n" +
    "1fpt3\n" +
    "qddscqpjlpnnlsneightkm6sixnine\n" +
    "hppd1xlkgsmtfxxbvcgzbdfournine\n" +
    "pqdmrhvxdqbrkgjdc36mbq\n" +
    "rpllrjvrvfourfivefour3\n" +
    "two5neightsevendmp1ninehjfvvplmfc\n" +
    "gppnq7\n" +
    "foursix81onefkhzshsfxlxgxjzdd\n" +
    "13five\n" +
    "3sevendjlgttvnsevensjpgsjt7\n" +
    "172\n" +
    "three69threefour\n" +
    "3tcnfpzpkz\n" +
    "5vxzzfhg24bznvrmsjmtfmfjgxdseven\n" +
    "szhmlqxfffiveeight71nine\n" +
    "8five89zjvjqtpmlqveight5two\n" +
    "5twopjlvzlrltv\n" +
    "sbjtbfqkshrrtlrxvvq97jrflnxcrnfive3\n" +
    "qhoneightfoureighttwo5xssdqmvljfivenine5\n" +
    "3eightsix3five9\n" +
    "treightwo3sqzninenine1sxk85\n" +
    "oneeightxklmdbfkqjfour9threetmlnine\n" +
    "lxfxplrqeightninethreeppfnzfvndjn8qrmsjq\n" +
    "5one55eightwog\n" +
    "tworlqkztqblj9ltxlshrhjlttnqzhsdbpzzzbxdn\n" +
    "53vvvsmxjvs\n" +
    "4nine2qpgvdtxldq4four8jnf\n" +
    "keightsevenhcvrpztgcvsxszqdlzd1threenpvszb\n" +
    "89eightvdvklpxfntwo\n" +
    "ndtqsrfjmtzgdptlp8pnnf4onelq\n" +
    "6threesevenfx\n" +
    "6fjbglhltcfdxcbnzlcrtwoneqx\n" +
    "3jxtvj1onemxbqxlnm6sevenjzkhljktcm\n" +
    "twogkljgjbxzhlnrdxkhqvsevenqqttpjnx3\n" +
    "jmdcbcllcv1\n" +
    "3twosevenxgtbzsfhrbxsgk9sevennine\n" +
    "372\n" +
    "52qzldrtxqxnfivekkdqqs54\n" +
    "gcmnp51hxhvdbk22gdvdfour\n" +
    "6bpdjtwoqmqtvzqfive\n" +
    "4zmfthreefivefoursix1csnrznptgr\n" +
    "hrdpbqfonefjqbbjrnine9onenine1\n" +
    "47bdtqmbdvhmsf3five86vhclmd\n" +
    "295two7four\n" +
    "3onenineseventkgxthreetblbmljhkhfour5\n" +
    "4four8fourthreek36\n" +
    "5rqnsvdhkbrvrltcqpsd\n" +
    "six4fourfourthreefour\n" +
    "4967\n" +
    "99\n" +
    "71seven9kcmclngvpmlkkfngssveight\n" +
    "79eight9six\n" +
    "3sevenp\n" +
    "seven69lxsllgjqdvfoureightfive\n" +
    "8six5grssfgfr78two\n" +
    "twomkpjc18fkkhlnkgkxfjnine\n" +
    "g8qcq9xqlzgzmmrf5vhm\n" +
    "zsix8ssfrjqbnztttvszlsqeighteight4slzcrnkvf\n" +
    "dmfive1ffprhgfnrx49\n" +
    "7cfdcptvvnvhfivetwo\n" +
    "18kqkxdlnhjbqoneszclkzljhnhqd\n" +
    "52lcclkxsix\n" +
    "three7five5cjtgpzjfoureight\n" +
    "53pchxqfpcfddsqzl7oneeight\n" +
    "ctjg84hqsjxfive\n" +
    "1znmjftpq7xbxt\n" +
    "nine71krj7fivenine\n" +
    "pgr6lfbhkpsjhhjpgqnxtxmkpdktnine21\n" +
    "xhkeightwo14four23eightqxhpct\n" +
    "x1\n" +
    "7357fivehfbbgdhzg\n" +
    "rktbdvm41seven\n" +
    "6fshmcmxdsfgxrcfvone\n" +
    "nndrdq7six\n" +
    "5two7r\n" +
    "one78gnsdkhkqfourfdsghnll6g\n" +
    "3sixht\n" +
    "96mbxlpgctgf1sixfivefour\n" +
    "2sixbcqskzpqbqtt8sixrtngznb2\n" +
    "twoone9fvmczldvtk\n" +
    "4jpfmgzgdhs\n" +
    "3ninefour\n" +
    "61nine\n" +
    "8kleightoneightrhf\n" +
    "51sixg\n" +
    "pckfpxzmrthreejvh8eighteight5\n" +
    "ssmgkkblkfive68eight2\n" +
    "nxkxdtckfb95bpdtrdhhltjdqpnine6\n" +
    "kqjkvndr3lfqthvmbrbfgzrbcntpcrd\n" +
    "44sixtwonineonefour\n" +
    "gtvlneighteight5961nine2\n" +
    "14lzxzbvbg4sixeightpthgz3\n" +
    "8814eighttph\n" +
    "7rpf8fivedkfivesfxgkjmniners\n" +
    "six6zsxzcfmcxzn2\n" +
    "four12dkgnmsjqtjp7zmzbsp\n" +
    "8two69six\n" +
    "three13six4three6one3\n" +
    "threedfmcmxgxzhglv36five\n" +
    "8kkjrbkmbt2\n" +
    "jhttwone3fivethree8ninehjgnvmxtkdcpmhhvrb\n" +
    "sixtwofourseven86zs8\n" +
    "26seven\n" +
    "28three6\n" +
    "qpsznsqqfb4ntcdf\n" +
    "9zbqnvnlgrjcnpmbkdmtvmdfouroneqctnnm2\n" +
    "onefivekpfrdbxcmn3sevenonerfzmcsvbjgtcxndv\n" +
    "seven814nskmxzpcnvfppntrssthree\n" +
    "74jfmrfkznsfiveeighttwofivethree1\n" +
    "sixgh8\n" +
    "fhnlhfour3jhrzjdsrfour4five\n" +
    "qgzblcqp9\n" +
    "jrk377gdrjfldpqmeightffrlxffive\n" +
    "36eightsixgvninezkl\n" +
    "3hshcq9r\n" +
    "dmrhgkv2njtwo95\n" +
    "6pktmsdxpmpvmpfc4eight\n" +
    "five1five6hnpbzpmcccnqpfive\n" +
    "lmsbmvmrrljf4ninesix4threertxtsvfour\n" +
    "419six\n" +
    "tstsix3six\n" +
    "37seven\n" +
    "sixtwovghcj32pj\n" +
    "x66four6\n" +
    "72twosixnvdcq2nvkmgbsb\n" +
    "kvxprh1tnlrpmcldsshh5kcdfxmbcbfour\n" +
    "2threekqqcvtxjrktkqpddqhfourpbqqcrgbdeighteight\n" +
    "rltdhqvnm8\n" +
    "sevenninetjvvfxcv7\n" +
    "bhmkxpvhrqkfive8fourtwotwo1lcbkk\n" +
    "threepcnnzhkbzfbhqtn3eight544rtsrtcc\n" +
    "eight7onekqdvzvsmxcpgfjlllhtptnrmv\n" +
    "47zsqd2pnsgjhpkxljpvnine\n" +
    "8ldxnsfour\n" +
    "two7vpjfvhtmqdcrqlonekkqrnc32\n" +
    "12znrsmjqf\n" +
    "eightsixeighttjjhqsevenns1qbkstj\n" +
    "pcpcrqshftwo4\n" +
    "sixtwoninenmffcmfldb81\n" +
    "five75pvngkvx9nnlttwotwonev\n" +
    "1739lkzpsfzdsixfoureight\n" +
    "threekqvbcfiveltbrtjjtdcchtjthxvztkjpd3eightsix\n" +
    "qrxtwonefive9\n" +
    "96zthtvk8228bmfllnc\n" +
    "tmnsgdz3fourtpmtcvtfqdcteighttm\n" +
    "rmpbtfqxmmtwokn5two\n" +
    "ninefive65\n" +
    "qzmthdvvzmxthf82fivesevenbvdt8dscnl\n" +
    "onenfhgqqpdrtxvzn961sxjhxlg2nmxzkbp\n" +
    "9eightone\n" +
    "fourfhnzmcfour6lshj\n" +
    "eightzlffkpcbrbjjpmjrz7tcgjonefourthree\n" +
    "twomdzv77four2437\n" +
    "bvcgtrxthg863\n" +
    "4fpmpsxzdshdszvckpxqkgfourxnrpp\n" +
    "one3sevenmfmlk\n" +
    "eightthreenvfp439\n" +
    "bm9\n" +
    "jssc74tlhvfdjs6kdxzrskxrdtfqnnkfczr\n" +
    "v2eightsix\n" +
    "eight2mflbkmeightqfivethreefour\n" +
    "fdchmls7\n" +
    "7cgtkzkdvkfour\n" +
    "one237\n" +
    "69tfpdbmcrbqq1\n" +
    "poneightfiveninefivetwosccxmtbf28\n" +
    "87sevenpzbjhjvqonetwo\n" +
    "xsbsqpdlp9threejpjmrctbkrjrsevenone\n" +
    "cmhxdcpl85jhtpnttwonzlcrcfivevxxqn\n" +
    "1zxccxdpkl9tdqkgfxsevenvhlrmvfhvvzdzbk\n" +
    "lqmnvtdqngqjh355\n" +
    "mcsttwo43bsdrtt7three9bhlh\n" +
    "pvmtwonefour8eight8\n" +
    "2tgcpztjnqkldhshbmxnm\n" +
    "5zqkkcnnsh3\n" +
    "vqfmjzln6xnrpnrpqkdpqfgxfnine2\n" +
    "87eighttwo1\n" +
    "sevenxrdhnpz87zzjzhxcbbxqxeightsixoneightssl\n" +
    "pdpgbbhpzzmhqfhkprgx1twoonethree\n" +
    "gggfnvtxvpsix6slxrninenine56\n" +
    "dxbhdfrvgqkhch5seveneight\n" +
    "7five3\n" +
    "fourfive1fourptggnine\n" +
    "three6npf45kjrbrg94nine\n" +
    "4twonev\n" +
    "4rgpf98two\n" +
    "7chcnzghmcznftwo5\n" +
    "dvskzxcgnljmgxfntwo73\n" +
    "qboneight5nine1vftwotwo\n" +
    "54lqlzgjqctwosix\n" +
    "zxqnine57\n" +
    "3onethree\n" +
    "eightfive2xxxtwoblfjhlq9b\n" +
    "6ninesqvjsrz813\n" +
    "6734\n" +
    "2jcxkckrj7crncbonevskt\n" +
    "167fivef1\n" +
    "three9five2eightfivetpdlpxljgnineone\n" +
    "9two6five\n" +
    "xxktwoone2crphztrtndrjgs\n" +
    "gcjzskxzmtwo45seventwoqvzpfive\n" +
    "8phdzrrlkhqjrmlgshlmonefggsnslj\n" +
    "threer3oneeightfive43\n" +
    "six1one\n" +
    "dzoneight8\n" +
    "sdztwoneghxmqxlgv68\n" +
    "9onecjone9ppvlt\n" +
    "2svml3fourfl6five\n" +
    "clknqq83ninefive\n" +
    "1tgfkdnqgoneightzf\n" +
    "9onesixfiveqcclnl\n" +
    "onedvchs4\n" +
    "strmhlxs2threefouroneseven\n" +
    "dpbxhlgkzbtwo32nrdtwo\n" +
    "seven38sixfivehlkdsj12\n" +
    "eightfive6\n" +
    "8sevenfour8mknvzhfnzvbjplldpqkvvrcrmfourfive\n" +
    "xmzjtktmsixsix2ninesvqgxc\n" +
    "7fourbpn1four\n" +
    "8nineqksmfivevdknb\n" +
    "8kfv4ldzf\n" +
    "71fiveeight\n" +
    "bbmtpsdbnktndcnthreethree2jeightsevenxl\n" +
    "ntggphnine3\n" +
    "6vfb5\n" +
    "9pqjp3fivedssspd\n" +
    "pmsixeight7x6\n" +
    "1nine5sixoneightmm\n" +
    "threefbhsjcqrstdzkfgsllpktqljnlsevengbvpmvhlthree5two\n" +
    "9rqfdgxl4pgfbdsfonedbmjqthnsevenone\n" +
    "ccqknlg29bzxdrdx\n" +
    "vtbjqtjhr23\n" +
    "sevenvstvhd1ninesix\n" +
    "sixdjszthree7\n" +
    "6jhnj4\n" +
    "2fivenjrfkz\n" +
    "one55\n" +
    "69fourvttjxr\n" +
    "kqpqtkss7lxfxsfsmxqkfpcrjm\n" +
    "459xr\n" +
    "46nzsfive\n" +
    "s4jhbqgpmsninesixfivefiveone\n" +
    "4twofivefive\n" +
    "528nmtcfptktmfivesixfour\n" +
    "78qnkp\n" +
    "zbgrb4mskvlrkcftbpjr2twones\n" +
    "tvcjhbv4nine\n" +
    "three6mxsxvlljdnsgtzrfouroneightlp\n" +
    "6jc7two\n" +
    "one9kmkrvjrzbv6eight1seven9seven\n" +
    "fivesixstjrxhn7zmjthsdk3fcjsq6\n" +
    "ncbzqeightfivetbpmzrvp44ctpjhg\n" +
    "sevenrgvgkzktvjdd92\n" +
    "5eightsj\n" +
    "83nine7hzjvjxmbn\n" +
    "sgspsggkbzfour9\n" +
    "two5fivetwofive41eightwosm\n" +
    "onejmk5eight\n" +
    "nine11\n" +
    "xlhx53qrnvqfiveclj7six\n" +
    "oneeightone1five8one14\n" +
    "56d3\n" +
    "5sevenseven9dnhkhhpjzbqkrt31\n" +
    "r6one\n" +
    "sevendh46\n" +
    "eighttwofivesevennine915eightwomjk\n" +
    "four26three\n" +
    "sixrspdrhltrseven3\n" +
    "3bf1two\n" +
    "6ts\n" +
    "sevenhnvgvkhztsqbqcvm17btpzrrrfpsnr\n" +
    "eight8fourldzrzhpmppkcfcchtzpteightthree5\n" +
    "124\n" +
    "379qtfive\n" +
    "4pp\n" +
    "128pqgtqrjdhlrfivesixthree\n" +
    "f7ninesix\n" +
    "16hqkxjnmd\n" +
    "9sixsix98qhblkzh\n" +
    "13nine8glvsfkrqs\n" +
    "ninegdnhsfgckc7two\n" +
    "onenine69lzqx7gxhcdcg34\n" +
    "67993fivexcx\n" +
    "nine6dbqrthree9five6bone\n" +
    "zvfmz6thgmqgqsvnqpxtdx575\n" +
    "eighteight2\n" +
    "five2five\n" +
    "lprqsrxqceighttwo744mptdngcgmchkg\n" +
    "1seven3ztfhcsrkdj76rmjz8\n" +
    "h4fiveeightfournineblvhhnnqpsix\n" +
    "sixk4\n" +
    "nine7vhpkkztwo\n" +
    "8jfrfchzpk54sixcfbdfrccpv3\n" +
    "9zkxnqjfzcrdseven8ninefivenine\n" +
    "ninefivenrfmttdq9vgtnqsxcmh\n" +
    "5tgjvsix5\n" +
    "722fvzzn\n" +
    "23threethree\n" +
    "7two5hszrj5nineonethreedp\n" +
    "2lpdzpzeightfive2onethree\n" +
    "lptvrd5qjnstntpld44eight6bflqd\n" +
    "ldh1three\n" +
    "tx9kgbrrvthreezkxhpn6\n" +
    "g5gks6fivel\n" +
    "hlblkd3threedcqhbtmktvtzqrmjhgtgtxnfbbdffmckbqxxp\n" +
    "dfjmnine71vfndzz\n" +
    "66eightfivepzqvsrlrr5\n" +
    "seven2threeninemcmlhfmkndhtdeightthreethree\n" +
    "6ktfgglmnvjgxsevenfourjzgp6eight\n" +
    "76zvbblfrthreeeight2ninefive\n" +
    "fivetgprhplmsmhslrtpr31six4\n" +
    "sevensevenone71rgqb6three8\n" +
    "34htvldclbxmeightwon\n" +
    "five1klzmf3\n" +
    "5dqpfivethree4\n" +
    "p6\n" +
    "xrtwone719\n" +
    "tmtwonefive3sevenqqpz8twotdsn6\n" +
    "qvcdkggrh644\n" +
    "899tnqhhzcjxxllmp139prgx\n" +
    "sixnrsgvmrggcl6\n" +
    "ccjq3one\n" +
    "5threejbhlrrlone1four\n" +
    "ninefive1ninevhndvmrbqzcnlccptbvl\n" +
    "3sevenonepnjxhkbtc\n" +
    "3ninelck34eight\n" +
    "jmjcc88trmxvsvkgxdjlh78jjtwo\n" +
    "mpfpnqqrsspmdjpkmrrlljrlsddnsix38three\n" +
    "mtttwo97\n" +
    "4xfnjbsplqnxtns13qlsnbhn\n" +
    "eight69eight\n" +
    "two6dtrfmgh4\n" +
    "qtgvqlzp175zxt5\n" +
    "sgmqvl9tmnthree2\n" +
    "db47six6nkgdqvc\n" +
    "6jrsixlldvpn2onekrqninejh\n" +
    "gdrqhbkpg3one\n" +
    "7threeseven8threegqlml6mjmtc2\n" +
    "nptwothree8five\n" +
    "8kxmjpnctddeightnine5twonevzf\n" +
    "threefour7fivelhvxvhlqzfn\n" +
    "spfgjxkcnfourllmv3v9four\n" +
    "7xzksddd7v8pjrv4five\n" +
    "68fq1four\n" +
    "threel6dd7one\n" +
    "pnrsevenseven5four95\n" +
    "4sevenqlzjjcdsvfdtzcjp\n" +
    "1kxfmrsix58ninenrmmlvtd\n" +
    "743threeqfxmmtvkczhteight\n" +
    "bslvhvlspr8dsmhjlrcfjsixnine\n" +
    "2mpjmtrrnineeightklxflnvgr\n" +
    "gxnzcrf4xvgcgb9one368\n" +
    "4three5j28xl\n" +
    "2seventkdnfrkvnd7\n" +
    "7llbkvzblfdtwo667six\n" +
    "two7onethree2fivesixhgjg\n" +
    "gthreelprkltjbqp7sevensix\n" +
    "q41cpcpjh\n" +
    "nine42fivefzztjknfv\n" +
    "five3kblrgsonedxjhsnxfour56\n" +
    "fckqjbs1cbblpbvtxdlcvtwotwo\n" +
    "9xvjszgkbcfourninerp8nine\n" +
    "vmlx27oneqzmffghcmfpn47\n" +
    "tjschpthreecbb6sclbfivejzlbd\n" +
    "77sfzkxdfdjnbnseven3knnqgvjbm\n" +
    "threeqgfcrn2\n" +
    "four7qcrxlcjsklhjcsz2731\n" +
    "sixreightsixqhflvseven8\n" +
    "1xxngrjnfsixfiveslrfivenkplbgnqxg\n" +
    "onefnhbcjqrthree7jlbcfgdl5\n" +
    "81oneightrgr\n" +
    "sixmqgdfgscr6three\n" +
    "sixxlcsix2\n" +
    "1zrqllfszlhqgp2\n" +
    "pcvrlxfml5znrjc542\n" +
    "pctzcvgrfj82\n" +
    "jnrlqsptfivetwokghkr8sevenlzdf\n" +
    "kfbdrtgtgsix9sevenone\n" +
    "ppzqjzvvfive39eighteightthree\n" +
    "bzblbmns62seven7jvdgxknx1one\n" +
    "foureightsevenmtwo7\n" +
    "3dxbt6h\n" +
    "7phdxhtsbmfzmhzlsh3four\n" +
    "fsrcjfour2kllnxdbfhnine3six\n" +
    "dp6sevenseven\n" +
    "nqf3pv7\n" +
    "fivesckjvndbf1eightfivejqzcsn\n" +
    "eightqxbx3jdzmcsvrpv9fplreightzdrlbpfj\n" +
    "one6twoeightkrrfdgrttxvthgfour\n" +
    "sevenseven3sixsdrtj\n" +
    "rstsevensix4oneseven7mrccrxmht\n" +
    "fourthreehjthr8five\n" +
    "fourxmxncslkq71\n" +
    "seven1b5two\n" +
    "3four9eightfour34\n" +
    "76one6four\n" +
    "sixsixpzghqfqndvpcmzt4tftxxpjbghs\n" +
    "fouronenine7eightwot\n" +
    "two77mplckblrclfqgpgsx24seveng\n" +
    "eight6twoeight18fczfn5four\n" +
    "7dxqshsmhrvbnfgjq5\n" +
    "nine52three\n" +
    "3thbtwo\n" +
    "two9sixeightoneeight\n" +
    "mklp1qqgkgcceightfour77\n" +
    "13onermtxflmnmq8qxhkhxthree2\n" +
    "397rhmknine96rzfgbr\n" +
    "8fourseveneighthb67\n" +
    "89625t\n" +
    "fbfxgqsqhthree74seven5\n" +
    "8threegnqhhpfx\n" +
    "zdsfs682\n" +
    "76lqkvfhtdpseven4lfpvkxjgqtwobbrz\n" +
    "7zthreesevenfour9four\n" +
    "ninefc6eight4two5oneighttfn\n" +
    "eight32\n" +
    "eighteight6lqgrgbntgkkzfqdjhxtwo\n" +
    "8vdzgsqnsix551\n" +
    "6klxfrfqzbsrnxmmdbnqbvfpzcjtx5two36\n" +
    "nhcdmxpvg5kmmknrnine\n" +
    "17tpsvtclthree\n" +
    "five84eightfjrznfsrb\n" +
    "fjzfb6onefourhtlmvlns\n" +
    "zqmmfdkl8\n" +
    "3sixeightnkgpssqnkrsclmshzzfhxxhvxlsljgfgnltbpc1twoneqd\n" +
    "8frbccqkvdtwoc\n" +
    "zeightwoeightptmkdhx3eightnineqx4\n" +
    "pbfnine6three8six5jtxmeight\n" +
    "eight78\n" +
    "1bhlgn5five\n" +
    "xnhhlgfrqbgfhhnvllhptfh3\n" +
    "ljjllzbbffpxcjrztzthreermg6fzqqpd\n" +
    "72mmjrfjvlzone3threethreesix\n" +
    "fiveonecfsfsix74twocllbfnptkgttf"

console.log("part1", data.split("\n").map((x) => {
    const chars = x.match(/\d/g).join();
    return parseInt(`${chars[0]}${chars[chars.length - 1]}`)
}).reduce((a, b) => a + b, 0));


const dictionary = {
    "one": 1, "1": 1,
    "two": 2, "2": 2,
    "three": 3, "3": 3,
    "four": 4, "4": 4,
    "five": 5, "5": 5,
    "six": 6, "6": 6,
    "seven": 7, "7": 7,
    "eight": 8, "8": 8,
    "nine": 9, "9": 9,
}
const keys = Object.keys(dictionary);

console.log("part2", data.split("\n").map((x) => {
    let numbers = [];
    while (x.length > 0) {
        for (let i = 0; i < keys.length; i++) {
            if (x.startsWith(keys[i])) {
                numbers.push(dictionary[keys[i]]);
            }
        }
        x = x.substring(1, x.length);
    }
    return parseInt(`${numbers[0]}${numbers[numbers.length - 1]}`);
}).reduce((a, b) => a + b, 0));



